#define __CONFIG_H__

// Serial
#define SERIAL_BAUD 115200
#define SERIAL_BUFFER_LEN 100

#define LTE_SERIAL_BAUD 57600 
#define LTE_SERIAL_RX 2
#define LTE_SERIAL_TX 3
#define LTE_SERIAL_BUFFER_LEN 100
// SD Card
